Gps integration
afosorio/tmcgr7 pull request #17
Opened 2019-11-23 18:38 UTC by lauramdelarosa

en este pull request esta la integracion del gps y se trae el pais donde esta el usuario actualmente
y esta la separacion de versiones en el gradle

2019-11-23 19:25 UTC, afosorio requested changes
Hola Lau!  sería bueno separar de una vez la funcionalidad del Main Activity

2019-11-27 03:19 UTC, afosorio approved these changes
ok

2019-11-27 03:43 UTC, afosorio approved these changes

2019-11-27 17:14 UTC, afosorio approved these changes
Ok, busquemos la aprobación de Esteban para hacer el merge!!! Gracias Lau.

2019-11-27 19:09 UTC, EstebanPosada approved these changes

2019-11-27 19:28 UTC, merged